# Variables
@baseUrl = http://localhost:3333

# Health check
# @name getcheck
GET {{baseUrl}}/health

###

#Get rooms
# @name getRoom
GET {{baseUrl}}/rooms

###

#Create room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "Sala de teste",
    "descripition": "descrição de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

#Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

#Create question
# @name createQuestion
POST {{baseUrl}}/rooms/27856056-3a67-4271-b4cd-78b51c0a6891/questions
Content-Type: application/json

{
    "question": "O que é Vue.js e a sua diferença em relação ao Angular?"
}

###